max_epochs: 50
accelerator: gpu
devices: ???
precision: bf16-mixed
gradient_clip_val: 1.0
strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  timeout:
    _target_: datetime.timedelta
    minutes: 15
